# 데이터과학 파이썬 10장 도전문제와 심화문제 풀이

### 심화문제 10.1

In [1]:
import numpy as np

num_arr = np.arange(1,21)
print(num_arr)

print(num_arr[::-1])

print(num_arr.sum())

num_arr = num_arr.reshape(5, 4) # 5행 4열의 배열로 변경
print(num_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
210
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


### 심화문제 10.2

In [2]:
import numpy as np

n_arr = np.arange(25).reshape(5,5)

In [3]:
import numpy as np

n_arr = np.arange(25).reshape(5,5)

print('첫 원소 :', n_arr[0][0])
print('마지막 원소 :', n_arr[-1][-1])

첫 원소 : 0
마지막 원소 : 24


In [4]:
import numpy as np

n_arr = np.arange(25).reshape(5,5)

slice_arr = (n_arr[:2])
print(slice_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
import numpy as np

n_arr = np.arange(25).reshape(5,5)

slice_arr = (n_arr[2:])
print(slice_arr)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
import numpy as np

n_arr = np.arange(25).reshape(5,5)

slice_arr = (n_arr[:, ::2])
print(slice_arr)

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [7]:
import numpy as np

n_arr = np.arange(25).reshape(5,5)

slice_arr = (n_arr[::2, ::2])
print(slice_arr)

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


In [8]:
import numpy as np

n_arr = np.arange(25).reshape(5,5)

slice_arr = (n_arr[:2])
slice_arr = slice_arr.reshape(5, 2)
print(slice_arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### 심화문제 10.3

In [9]:
import numpy as np

np.random.seed(100)

a = np.random.rand(3, 3, 3)

print(a)

[[[0.54340494 0.27836939 0.42451759]
  [0.84477613 0.00471886 0.12156912]
  [0.67074908 0.82585276 0.13670659]]

 [[0.57509333 0.89132195 0.20920212]
  [0.18532822 0.10837689 0.21969749]
  [0.97862378 0.81168315 0.17194101]]

 [[0.81622475 0.27407375 0.43170418]
  [0.94002982 0.81764938 0.33611195]
  [0.17541045 0.37283205 0.00568851]]]


In [10]:
import numpy as np

np.random.seed(100)

a = np.random.rand(3, 3, 3)

print('a의 원소들 중 최댓값 :', np.max(a))

a의 원소들 중 최댓값 : 0.9786237847073697


In [11]:
import numpy as np

np.random.seed(100)

a = np.random.rand(3, 3, 3)

print('a의 원소들 중 최댓값의 위치 :', np.argmax(a))

a의 원소들 중 최댓값의 위치 : 15


### 심화문제 10.4

In [12]:
import numpy as np

n_arr = (np.arange(1, 26) % 2).reshape(5, 5)

print(n_arr)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [13]:
import numpy as np

n_arr = (np.arange(1, 26) % 2).reshape(5, 5)

sum_arr = n_arr.sum(axis = 0)

print('행렬의 행 방향 성분의 합 : ')
print(sum_arr)

행렬의 행 방향 성분의 합 : 
[3 2 3 2 3]


### 심화문제 10.5

In [14]:
import numpy as np

a = np.arange(0, 32).reshape(4, 4, 2)

a = a.flatten()

print('10번째 원소 :', a[9])
print('20번째 원소 :', a[19])

10번째 원소 : 9
20번째 원소 : 19


### 심화문제 10.6

In [15]:
import numpy as np

x1 = [ i for i in range(100) ]
x2 = [ i + np.random.randint(1, 10) for i in range(100) ]
x3 = [ i + np.random.randint(1, 50) for i in range(100)]
x4 = [ np.random.randint(1, 100) for i in range(100) ]

result = np.corrcoef( [x1, x2, x3, x4] )
print(result)

[[1.         0.99645022 0.90571243 0.13115943]
 [0.99645022 1.         0.90690719 0.1288173 ]
 [0.90571243 0.90690719 1.         0.04719846]
 [0.13115943 0.1288173  0.04719846 1.        ]]
